package app.aaps.pump.ypsopump

import app.aaps.pump.ypsopump.history.YpsoHistoryEntry
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test

class YpsoHistoryEntryTest {

    // Payload fields were packed independently with Python struct.pack('<IBHHHIH', ...); the final
    // two bytes were generated by an independent implementation of the documented CRC algorithm.
    private val fixture = "785634129abc00efbe3412efcdab8988774ead".hex()

    @Test
    fun `strict fixture exposes unsigned little endian fields without inventing an epoch`() {
        assertEquals(
            YpsoHistoryEntry(
                factorySeconds = 0x12345678,
                eventType = 0x9a,
                value1 = 0x00bc,
                value2 = 0xbeef,
                value3 = 0x1234,
                sequence = 0x89abcdef,
                index = 0x7788,
            ),
            YpsoHistoryEntry.decodeWire(fixture),
        )
    }

    @Test
    fun `raw fallback trailing data and corrupt CRC are rejected`() {
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOfRange(0, 17)))
        assertNull(YpsoHistoryEntry.decodeWire(fixture + 0))
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOf().apply { this[4] = (this[4].toInt() xor 1).toByte() }))
    }

    private fun String.hex(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
