package app.aaps.pump.ypsopump

import app.aaps.pump.ypsopump.history.YpsoHistoryEntry
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class YpsoHistoryEntryTest {

    // Payload fields were packed independently with Python struct.pack('<IBHHHIH', ...); the final
    // two bytes were generated by an independent implementation of the documented CRC algorithm.
    private val fixture = "785634129abc00efbe3412efcdab8988774ead".hex()
    // Shape-only fixtures transformed from protected target rows by replacing identifying
    // time/sequence values, preserving the evidenced field layout, then recomputing CRC independently.
    // Protected source capture set SHA-256: e3d8ae3d842e32c087a7597b50133cd02d88faeb725d4c0747082ce70b644b82.
    private val transformedTargetShape = "785634120e030000000000efcdab89000094fe".hex()
    private val transformedTargetShapes = mapOf(
        "7856341202960000000000650000000000ac4d" to Triple(2, 150, 0),
        "78563412032c010f0000006600000000001989" to Triple(3, 300, 15),
        "78563412046400002eef2c670000000000dbc6" to Triple(4, 100, 11776),
        "785634120996000f000000680000000000d6e4" to Triple(9, 150, 15),
        "785634120ac8001e000000690000000000808d" to Triple(10, 200, 30),
        "785634120e0a00000000006a0000000000ce63" to Triple(14, 10, 0),
        "785634121091ff0000c9006b0000000000f3e8" to Triple(16, 65425, 0),
    )
    // Type 6 is independently published as BASAL_PROFILE_CHANGED by two Ypso protocol
    // implementations. This contract wire verifies that it uses the same strict 19-byte schema;
    // it is not represented as a transformed target capture.
    private val activeProfileChangedContractShape = "78563412060000000000006c00000000001319".hex()

    @Test
    fun `strict fixture exposes unsigned little endian fields without inventing an epoch`() {
        assertEquals(
            YpsoHistoryEntry(
                factorySeconds = 0x12345678,
                eventType = 0x9a,
                value1 = 0x00bc,
                value2 = 0xbeef,
                value3 = 0x1234,
                sequence = 0x89abcdef,
                index = 0x7788,
            ),
            YpsoHistoryEntry.decodeWire(fixture),
        )
    }

    @Test
    fun `raw fallback trailing data and corrupt CRC are rejected`() {
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOfRange(0, 17)))
        assertNull(YpsoHistoryEntry.decodeWire(fixture + 0))
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOf().apply { this[4] = (this[4].toInt() xor 1).toByte() }))
    }

    @Test
    fun `transformed target row preserves evidenced stop event layout`() {
        val entry = checkNotNull(YpsoHistoryEntry.decodeWire(transformedTargetShape))
        assertEquals(14, entry.eventType)
        assertEquals(3, entry.value1)
        assertEquals(0, entry.index)
    }

    @Test
    fun `transformed target rows preserve every evidenced supported layout`() {
        for ((wire, expected) in transformedTargetShapes) {
            val entry = checkNotNull(YpsoHistoryEntry.decodeWire(wire.hex()))
            assertEquals(expected.first, entry.eventType)
            assertEquals(expected.second, entry.value1)
            assertEquals(expected.third, entry.value2)
            assertEquals(0, entry.index)
        }
    }

    @Test
    fun `active profile changed contract row uses the strict common wire layout`() {
        val entry = checkNotNull(YpsoHistoryEntry.decodeWire(activeProfileChangedContractShape))
        assertEquals(6, entry.eventType)
        assertEquals(0, entry.value1)
        assertEquals(0, entry.value2)
        assertEquals(0, entry.value3)
        assertEquals(0, entry.index)
    }

    @Test
    fun `constructed entries cannot truncate values outside the wire widths`() {
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0x1_0000_0000L, 0, 0, 0, 0, 0, 0)
        }
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0, 0x100, 0, 0, 0, 0, 0)
        }
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0, 0, 0, 0, 0, 0, 0x1_0000)
        }
    }

    @Test
    fun `identity fingerprint survives an in-place TBR terminal rewrite`() {
        val active = YpsoHistoryEntry(842_796_897, 9, 150, 15, 0, 47_881, 0)
        val cancelled = YpsoHistoryEntry(842_796_897, 10, 150, 1, 0, 47_881, 8)
        assertEquals(active.fingerprint(), cancelled.fingerprint())
        org.junit.jupiter.api.Assertions.assertNotEquals(active.stateFingerprint(), cancelled.stateFingerprint())
    }

    private fun String.hex(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
