package app.aaps.pump.ypsopump

import app.aaps.pump.ypsopump.history.YpsoHistoryEntry
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class YpsoHistoryEntryTest {

    // Payload fields were packed independently with Python struct.pack('<IBHHHIH', ...); the final
    // two bytes were generated by an independent implementation of the documented CRC algorithm.
    private val fixture = "785634129abc00efbe3412efcdab8988774ead".hex()
    // Shape-only fixture transformed from a protected target type-14 row by replacing identifying
    // time/sequence values, preserving the evidenced field layout, then recomputing CRC independently.
    // Protected source capture set SHA-256: e3d8ae3d842e32c087a7597b50133cd02d88faeb725d4c0747082ce70b644b82.
    private val transformedTargetShape = "785634120e030000000000efcdab89000094fe".hex()

    @Test
    fun `strict fixture exposes unsigned little endian fields without inventing an epoch`() {
        assertEquals(
            YpsoHistoryEntry(
                factorySeconds = 0x12345678,
                eventType = 0x9a,
                value1 = 0x00bc,
                value2 = 0xbeef,
                value3 = 0x1234,
                sequence = 0x89abcdef,
                index = 0x7788,
            ),
            YpsoHistoryEntry.decodeWire(fixture),
        )
    }

    @Test
    fun `raw fallback trailing data and corrupt CRC are rejected`() {
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOfRange(0, 17)))
        assertNull(YpsoHistoryEntry.decodeWire(fixture + 0))
        assertNull(YpsoHistoryEntry.decodeWire(fixture.copyOf().apply { this[4] = (this[4].toInt() xor 1).toByte() }))
    }

    @Test
    fun `transformed target row preserves evidenced stop event layout`() {
        val entry = checkNotNull(YpsoHistoryEntry.decodeWire(transformedTargetShape))
        assertEquals(14, entry.eventType)
        assertEquals(3, entry.value1)
        assertEquals(0, entry.index)
    }

    @Test
    fun `constructed entries cannot truncate values outside the wire widths`() {
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0x1_0000_0000L, 0, 0, 0, 0, 0, 0)
        }
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0, 0x100, 0, 0, 0, 0, 0)
        }
        assertThrows(IllegalArgumentException::class.java) {
            YpsoHistoryEntry(0, 0, 0, 0, 0, 0, 0x1_0000)
        }
    }

    private fun String.hex(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
